### ISSUE TITLE
fix(tests): resolve 4 pre-existing test failures in test_bot_detection.py

### ISSUE THREAD

**Issue by wmoore012** [wmoore012/youtube-music-analytics#6]
## Summary
4 out of 16 tests in `tests/test_bot_detection.py` are failing with pre-existing bugs that were hidden by earlier CI failures (Issues #2, #3, #4).

### 1. `test_normalize_and_strip_handles_zero_width_and_case`
**Error:** `AssertionError: assert 'CRAZY!!' == 'CRAZY!! '`
**Root Cause:** `_strip_emojis()` function is stripping trailing spaces after emojis
**File:** `tests/test_bot_detection.py:46`

### 2. `test_timestamp_link_and_whatsapp_telegram_lures`
**Error:** `assert 100.0 > 100.0`
**Root Cause:** Bot score threshold logic issue - benign_max equals bot_score (both 100.0)
**File:** `tests/test_bot_detection.py:167`

### 3. `test_burst_near_duplicates_across_users_and_videos`
**Error:** `assert False` (duplicate_count_local all zeros instead of >= 2)
**Root Cause:** Duplicate detection logic not working correctly
**File:** `tests/test_bot_detection.py:177`

### 4. `test_basic_bot_detector_interface`
**Error:** `TypeError: BotDetector.__init__() missing 1 required positional argument: 'config'`
**Root Cause:** BotDetector API changed but legacy compatibility test not updated
**File:** `tests/test_bot_detection.py:283`

## Impact
- **Severity:** Medium (tests failing but not blocking main functionality)
- **Scope:** Bot detection system only
- **CI Status:** These failures are now visible after fixing Issues #2, #3, #4 in PR #5

## Acceptance Criteria
- [ ] All 4 failing tests pass
- [ ] No new test failures introduced
- [ ] Bot detection functionality verified with integration tests

## Related Issues
- Discovered while fixing #2, #3, #4 in PR #5
- CI workflow run: https://github.com/wmoore012/youtube-music-analytics/actions/runs/19459880906
